name: My CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@vv3.8.1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run my script with secret
        env:
          MY_SECRET: ${{ secrets.API_KEY_WEATHER}}
        run: index-584d7cd1.js

